parser:
  # regex to parse a main log line 
  # if a line doesn't match this, it will be rolled up into the previous line body
  line-regex: ^([0-9]{1,2}\s+[A-Za-z]+\s+[0-9]{4}\s+[0-9.:,]+)\s+\[([A-Z]+)\]\s+.*?((?:com|org|net)[a-zA-Z.0-9]+):\s*(.*)$
  # exception-class-regex: 
  
  # capture group fields/indexes
  fields:
    datetime: 
      index: 0
      format: dd MMM yyyy HH:mm:ss,SSS
    type: 
      index: 1
    source: 
      index: 2
    message: 
      index: 3
  
  # root log directory
  log-dir: "resources"
      
db: 
  type: mongo
  mongo:
    host: 127.0.0.1
    port: 27017
    db: treehunter
    
