parser:
  # regex to parse a main log line 
  # if a line doesn't match this, it will be rolled up into the previous line body
  regex: ^([0-9]{1,2}\s+[A-Za-z]+\s+[0-9]{4}\s+[0-9.:,]+)\s+\[([A-Z]+)\]\s+.*?((?:com|org|net)[a-zA-Z.0-9]+):\s*(.*)$
  
  # capture group fields/indexes
  fields:
    datetime: 
      index: 0
      format: dd MMM yyyy HH:mm:ss,SSS
    type: 
      index: 1
    class: 
      index: 2
    message: 
      index: 3